version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
    - ./src:/app
    links:
    - php-fpm

  php-fpm:
    build: ./docker-build-context
    volumes:
    - ./src:/app
